modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/suppergerrie2/PanoramaMod/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
updateJSONURL="https://raw.githubusercontent.com/suppergerrie2/PanoramaMod/master/update.json"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/panorama-creator"
credits="liachmodded for making runorama which helped a lot and Cadiboo for his example on keybindings"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"